language: node_js

node_js:
  - 0.10

cache:
  directories:
    - node_modules

sudo: false

env:
  - BROWSERS="SauceLab(chrome,Windows 7,37)"
  - BROWSERS="SauceLab(chrome,Windows 7,43)"
  - BROWSERS="SauceLab(chrome,OS X 10.10,37)"
  - BROWSERS="SauceLab(chrome,OS X 10.10,43)"

  - BROWSERS="SauceLab(chrome,Windows 7,37)" ASYNC=1
  - BROWSERS="SauceLab(chrome,Windows 7,43)" ASYNC=1
  - BROWSERS="SauceLab(chrome,OS X 10.10,37)" ASYNC=1
  - BROWSERS="SauceLab(chrome,OS X 10.10,43)" ASYNC=1
