language: node_js

node_js:
  - 0.10

cache:
  directories:
    - node_modules

sudo: false

before_script:
  - node ./check-bluebird-version.js

env:
  - HACKBLUEBIRD=2.9.24 BROWSERS="SauceLab(chrome,OS X 10.10,43)"
  - BROWSERS="SauceLab(chrome,OS X 10.10,43)"
